### ISSUE TITLE
Action leaves .msi file in checkout directory on Windows

### ISSUE THREAD

**Issue by krlmlr** [ankane/setup-mariadb#1]
https://github.com/r-dbi/RMariaDB/runs/1483985818?check_suite_focus=true#step:14:89

>      Non-standard file/directory found at top level:
>         'mariadb.msi'

I can add to `.Rbuildignore` for now.

Thanks for providing these actions, they save a ton of time!

**Comment by ankane** [comment]
Hey @krlmlr, thanks for reporting! Should use a temporary directory for the download now.

**Comment by krlmlr** [comment]
Thanks, works for me.
