### ISSUE TITLE
Need quotes around version?

### ISSUE THREAD

**Issue by krlmlr** [ankane/setup-mariadb#12]
```yaml
      with:
        mariadb-version: 11.0
```

gave me: `Invalid MariaDB version: 11` : https://github.com/r-dbi/RMariaDB/actions/runs/5262998831/jobs/9512728749?pr=299#step:7:100

This seems to work:

```yaml
      with:
        mariadb-version: "11.0"
```

**Comment by ankane** [comment]
Hi @krlmlr, it'll need quotes since the workflow YAML parsing doesn't differentiate between 11 and 11.0: https://github.com/actions/runner/issues/849

**Comment by krlmlr** [comment]
Well, yes, but as a user, I don't care :-)

It's only a little work to treat a numeric 11 as an 11.0, and act accordingly. Would you review a PR?
