### ISSUE TITLE
Feature: Pass options to installer

### ISSUE THREAD

**Issue by mdeweerd** [ankane/setup-mariadb#17]
Possibly installation could speed up a bit by installing only the needed features which needs the possibility to pass trhough options to the installer.

https://mariadb.com/kb/en/installing-mariadb-msi-packages-on-windows/#features

**Comment by ankane** [comment]
Hi @mdeweerd, thanks for the suggestion! I just tried removing different features, but it doesn't appear to help much, so I don't think it's worth adding an option (the `DBInstance` feature seems to take most of the time).
