### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by Cyberboss** [ankane/setup-mariadb#19]
As of 12 hours ago from creating this issue.

https://downloads.mariadb.com/MariaDB/mariadb-11.4.2/winx64-packages/mariadb-11.4.2-winx64.msi is 404'ing

https://github.com/tgstation/tgstation-server/actions/runs/11153874229/job/31003041075?pr=1946

**Comment by ankane** [comment]
Hi @Cyberboss, thanks for reporting. Fixed in #20.

**Comment by Cyberboss** [comment]
Thank you!
